name 'cmurphy-jasm'
version '0.1.0'
source 'git://github.com/cmurphy/puppet-jasm.git'
author 'cmurphy'
license 'Apache 2.0'
summary 'Just Another SSH Module'
project_page 'http://github.com/cmurphy/puppet-jasm'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
